name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  release:
    types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

env:
  REGISTRY: docker.io

jobs:
  build:
    strategy:
      matrix:
        image:
          - name: modelzai/llm-chatglm-6b-int4
            dockerfile: ./images/chatglm-6b-int4/Dockerfile
          - name: modelzai/llm-bloomz-560m
            dockerfile: ./images/bloomz-560m/Dockerfile
          - name: modelzai/llm-chatglm-6b
            dockerfile: ./images/chatglm-6b/Dockerfile
          - name: modelzai/llm-llama-7b
            dockerfile: ./images/llama-7b/Dockerfile
          - name: modelzai/llm-fastchat-t5-3b
            dockerfile: ./images/fastchat-t5-3b/Dockerfile
          - name: modelzai/llm-vicuna-7b
            dockerfile: ./images/vicuna-7b/Dockerfile
          - name: meta-llama/Llama-2-7b-hf
            dockerfile: ./images/llama-2-7b/Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERIO_MODELZ_USERNAME }}
          password: ${{ secrets.DOCKERIO_MODELZ_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image.name }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
